### ISSUE TITLE
Are UseTls and CertificateCheck implemented?

### ISSUE THREAD

**Issue by lixxbox** [fvanroie/MqttClientPlugin#17]
UseTls and CertificateCheck are mentioned in the documentation, but are striked through. Have these functions been integrated in the meantime, or is their implementation still planned?

I have problems connecting to a broker. According to tests with mqtt explorer it needs user/pass , tls encryption enabled and certificate check disabled.

**Comment by fvanroie** [comment]
This functionality is not implemented and isn't planned.

**Comment by lixxbox** [comment]
Thank you for the feedback! Even though it's unfortunate that it won't be implemented.

**Comment by fvanroie** [comment]
I open-sourced the code so you are free to implement new features and create a Pull Request.

**Comment by lixxbox** [comment]
I'm glad you pointed that out.
I completely understand the open-source approach and have contributed to other projects myself. If I had the skills to implement it, I would have gladly contributed my code here as well. 
However, if at some point I reach the limits of my programming abilities, this approach unfortunately doesn't help me much. :-(
