### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Pimmetje** [fvanroie/MqttClientPlugin#3]
Where can i find any connection issues? I found the library to load. But i am unable to get it to connect to my RabbitMQ MQTT server. Is there any way i can check this? (Sorry i am also a bit a rainmeter noob)

**Comment by fvanroie** [comment]
If you double-click the rainmeter icon, you have a button to Open Log window:

![image](https://user-images.githubusercontent.com/15969459/74688460-e6c96c00-51d7-11ea-946a-f020f3e48bb8.png)

There you can check for connection issues. What is the setup of you ini file? *(without the credentials of course)*

**Comment by Pimmetje** [comment]
Rainmaker.ini (or should it be placed somewhere else?)
```
[mqttServer]
Measure=Plugin
Plugin=MqttPlugin.dll
Server=fqdn.myserver
Username=myusername
Password=mypassword

[mTopic1]
Measure=Plugin
Plugin=MqttPlugin.dll
ParentName=mqttServer
Topic=/rainmeter/topic1
```

**Comment by fvanroie** [comment]
It should go into your Skins folder:  e.g. `%userprofile%\Documents\Rainmeter\Skins\Mqtt\test.ini`
Then Load the Mqtt\test.ini skin from the Rainmeter menu.

You also need a Meter object to show the actual values of the Measures:

```
[Rainmeter]
Update=1000
BackgroundMode=2
SolidColor=000000

[mqttServer]
Measure=Plugin
Plugin=MqttClient
Server=fqdn.myserver
Username=myusername
Password=mypassword

[mqttTopic1]
Measure=Plugin
Plugin=MqttClient
ParentName=mqttServer
Topic=rainmeter/topic1

[mqttTopic2]
Measure=Plugin
Plugin=MqttClient
ParentName=mqttServer
Topic=rainmeter/topic2

[Text]
Meter=STRING
MeasureName=mqttServer
MeasureName2=mqttTopic1
MeasureName3=mqttTopic2
X=5
Y=5
W=300
H=120
FontColor=FFFFFF
FontSize=24
Text="mqttServer: %1#CRLF#mqttTopic1: %2#CRLF#mqttTopic2: %3"
```

As you are new to Rainmeter, please have a look at the [Documentation](https://docs.rainmeter.net/). Rainmeter is unlike any other tool and getting the know the specific configuration options can be a challenge to new users. They also have a lot of examples of how to configure Rainmeter there.

**Comment by Pimmetje** [comment]
```
Plugin: Unable to load "MqttPlugin.dll" (error 126) (Hello World\helloworld.ini - [mqttServer])
```

**Comment by fvanroie** [comment]
You need to specify the name if the plugin as `Plugin=MqttClient`.

**Comment by Pimmetje** [comment]
Thanks for the help. I took the example now and set the server, username, password

I can add it to my screen. But it does not connect to the MQTT server and i haven't found a error in the log (config below server/username/password are fake

```
[Rainmeter]
Update=1000
BackgroundMode=2
SolidColor=000000

[mqttServer]
Measure=Plugin
Plugin=MqttClient
Server=rabbitmq.with.mqtt.fqdn
Username=rainmeter
Password=passwordforuserrainmeter

[mqttTopic1]
Measure=Plugin
Plugin=MqttClient
ParentName=mqttServer
Topic=mytopics/hello

[mqttTopic2]
Measure=Plugin
Plugin=MqttClient
ParentName=mqttServer
Topic=mytopics/world

[Text]
Meter=STRING
MeasureName=mqttServer
MeasureName2=mqttTopic1
MeasureName3=mqttTopic2
X=5
Y=5
W=300
H=120
FontColor=FFFFFF
FontSize=24
Text="mqttServer: %1#CRLF#mqttTopic1: %2#CRLF#mqttTopic2: %3"
```

**Comment by fvanroie** [comment]
Is the MQTT server running on port 1883 or a custom port? Are you able to connect with another client, like MQTT Explorer or mosquitto_sub using the same parameters?

**Comment by Pimmetje** [comment]
Yes, i just checked it.

**Comment by Pimmetje** [comment]
I tried on another computer. Now it works
