### ISSUE TITLE
Display images

### ISSUE THREAD

**Issue by Pimmetje** [fvanroie/MqttClientPlugin#4]
Would it be possible to display images that are send over MQTT? I am thinking about publishing some camera snaps to a topic and display them on any device that needs them. 
https://docs.rainmeter.net/manual/meters/image/

**Comment by fvanroie** [comment]
Since the payload is just an array of bytes, you should be able to save it to a file and use that as input for the Image meter. I haven't used the Plugin like this myself, but you can certainly give it a try.
