### ISSUE TITLE
How do I publish?

### ISSUE THREAD

**Issue by HHashi** [fvanroie/MqttClientPlugin#5]
Hi there,

First of all, thanks for taking the time to create this. It's great! I literally started playing around with Rainmeter today and with your plugin, I managed to successfully subscribe to a topic and output that as text on the screen.

I saw on the README.md that it's also possible to publish, so I was wondering if there's any documentation on that? I want to create a button that when clicked, publishes a message (integer between 0-100) to a topic.

Any help/pointers would be much appreciated!

**Comment by fvanroie** [comment]
Say you have a Client Measure like this:
```
[mqttClient]
Measure=Plugin
Plugin=MqttClient
ClientId=myRainmeterClient
Server=192.168.4.1
Port=1883
```

Then you can use the `&mqttClient:Publish(topic,payload)` function in your Actions like so:
```
[Button1]
Meter=Shape
Shape=Rectangle 0,0,50,50,5,5 | Fill Color 128,128,128,1 | StrokeWidth 0.25 | Stroke Color 255,255,255,255
LeftMouseUpAction=[&mqttClient:Publish(cmnd/sonoffpow_f1/Power,TOGGLE)]
```
Here `cmnd/sonoffpow_f1/Power` is the topic and `TOGGLE` is used as payload. Clicking the button in my case, toggles an MQTT enabled Tasmota switch.

**Comment by HHashi** [comment]
That's great, thank you very much for your help! :)
