### ISSUE TITLE
Release compiled DLL?

### ISSUE THREAD

**Issue by yankee42** [fvanroie/MqttClientPlugin#8]
Can the compiled DLLs be found anywhere or do I need to built this from source?

**Comment by fvanroie** [comment]
I've tried to make it as easy as possible to compile the project, but I understand this is a hurdle for non-developers that do not already have Visual Studio installed. I have created a Github action that automatically compiles the code and keeps the artifacts (dlls).

The goal is still to make a .rmskin for the MqttClient Plugin, *which includes the dlls and example files*, but until then you can download it in [the latest build action](https://github.com/fvanroie/MqttClientPlugin/actions/runs/399855728).

**Comment by yankee42** [comment]
Thanks a lot, very helpful!

**Comment by clientgithub** [comment]
Hi, plugin expired time, please build new .dll
Thank you and please continue project!

**Comment by fvanroie** [comment]
I've issued a rebuild

**Comment by clientgithub** [comment]
Thank you man !!!!

**Comment by wde-360** [comment]
Hi please could you do another rebuild its expired again. Have been using for a while now works great Thanks

**Comment by fvanroie** [comment]
It's still up [here](https://github.com/fvanroie/MqttClientPlugin/actions/runs/750101382).

**Comment by wde-360** [comment]
Thank you so much for the fast response, I was looking in the wrong place!!

**Comment by fvanroie** [comment]
No worries, enjoy :)

**Comment by fvanroie** [comment]
A new version has been [released](https://github.com/fvanroie/MqttClientPlugin/releases). From now on, these will include an .rmskin for easy installation.
